version: '3'

services:
  raisingthebar.bll:
    image: raisingthebarbll
    build:
      context: .
      dockerfile: ../RaisingTheBAR.BLL/Dockerfile

  raisingthebar.dal:
    image: raisingthebardal
    build:
      context: .
      dockerfile: RaisingTheBAR.DAL/Dockerfile

